In [1]:
import numpy as np

In [19]:
X = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [25]:
y = np.ones(len(X),)

In [26]:
y

array([1., 1., 1., 1.])

In [27]:
np.column_stack((y,X))

array([[ 1.,  1.,  2.,  3.],
       [ 1.,  4.,  5.,  6.],
       [ 1.,  7.,  8.,  9.],
       [ 1., 11., 12., 13.]])

In [31]:
def add_one(X):
    """
    Your code
    """
    y = np.ones(len(X),)
    A = np.column_stack((y,X))
    return A
add_one(X)

array([[ 1.,  1.,  2.,  3.],
       [ 1.,  4.,  5.,  6.],
       [ 1.,  7.,  8.,  9.],
       [ 1., 11., 12., 13.]])

In [38]:
def multiply(X,w):
    A = np.column_stack((np.ones(X.shape[0]),X))
    if A.shape[-1]==w.shape[0]:
        return A @ w
    return None
multiply(X,y)

array([ 7., 16., 25., 37.])

In [36]:
def multiply(X, w):
    X = np.column_stack((np.ones(X.shape[0]), X))
    if X.shape[1] == w.shape[0]:
        return X @ w
    return ("hoo")

In [37]:
multiply(X,y)

array([ 7., 16., 25., 37.])

In [39]:
import numpy as np
def loss(X,w,y):
    A = np.column_stack((np.ones(X.shape[0]),X))
    e = (A@w)-y
    return 0.5 * (np.transpose(e) @e)

In [40]:
def loss(X, w, y):
    X = np.column_stack((np.ones(X.shape[0]), X))
    e = (X @ w) - y
    return 0.5 * (e.T @ e)

In [41]:
loss(X,y,w)

NameError: name 'w' is not defined